logging:
  level: DEBUG

cors:
  origins:
    - "*"
  credentials: false

auth:
  verify_jwt: true
  allow_insecure_jwt_decode: false

keycloak:
  http_url: "http://keycloak:8080/"
  manage_url: "http://keycloak:9000/"
  realm: "restapi"
  client_id: "fastapi"
  client_secret: null
